name: geosci-labs

channels:
  - conda-forge
dependencies:
  - mamba
  - notebook
  - jupyterhub
  - jupyterlab
  - bokeh
  - conda-lock
  - ghp-import
  - git
  - jupytext
  - jupyter-resource-usage
  - matplotlib=3.4.3
  - numpy=1.21
  - nbgitpuller
  - pandas
  - pip
  - pillow
  - python=3.9
  - discretize
  - empymod
  - ipywidgets
  - mkl
  - pymatsolver
  - qtconsole
  - qtpy
  - scipy
  - scikit-learn
  - SimPEG
  - pip:
    - git+https://github.com/geoscixyz/geosci-labs
